### PR TITLE
[fix] Handle request errors on downloading files + delete temporary f…

### LINKED ISSUE #650: Error not caught when downloading a file.
The err from request is not caught here : 
https://github.com/cozy-labs/konnectors/blob/master/server/models/file.coffee#L92

In case an error occur, the file should be deleted from /tmp

### PR DESCRIPTION
**Pull request by ZeHiro**
…iles on error. Fixes #650

### CODE REVIEW

File: server/models/file.coffee [hunk 1]
```diff
@@ -70,14 +70,21 @@ File.createNew = (fileName, path, url, tags, callback) ->
         class: getFileClass mime
         mime: mime
 
+    # Clear the temporary file
+    clearTmpFile = (cb) ->
+        log.info "Deleting file: #{filePath}"
+        fs.unlink filePath, (err) ->
+            callback err, null if err?
+            cb()
```
Comment (nicofrand) [inline server/models/file.coffee]: Is that normal to call bath callback and cb if there is an error ? Shouldn't we call cb(err) ?

Comment (ZeHiro) [inline server/models/file.coffee]: I'll make it cleaner (only one cb)

**Comment by nicofrand** [comment]
Just tested it: the deletion seems to work fine:

```
GET /konnectors/ae5e99f2a0e44616b9ddd9a99f02326c 200 13.521 ms - 382
[2017-01-16 08:43:58:611] info - Captaintrain | Connected
[2017-01-16 08:44:12:493] info - Captaintrain | import for entry 012017 started.
GET /folders/e1dd469b404f02575a0ca21a600099ab 200 69.411 ms - 149
info - konnectors | Downloading file at https://www.trainline.eu/invoices/????/Trainline-Justificatif-2017-01-02.pdf?locale=fr...
GET /folders/e1dd469b404f02575a0ca21a60009a2e 200 11.199 ms - 135
info - konnectors | File at https://www.trainline.eu/invoices/????/Trainline-Justificatif-2017-01-02.pdf?locale=fr downloaded.
info - konnectors | Deleting file: /tmp/20170102_Captaintrain.pdf
error - konnectors | 
```

I don't know why there was an error though, is there an issue with the Trainline connector (still named "CaptainTrain" on my instance) or might this come from this PR ?
