### PR TITLE
Fix Ameli locales. fixes #609

### LINKED ISSUE #609: Ameli konnector
Custom field (bank_identifier) is required

### PR DESCRIPTION
**Pull request by ZeHiro**

### CODE REVIEW

File: client/app/locales/fr.coffee [hunk 1]
```diff
@@ -23,7 +23,7 @@ module.exports =
     'login': 'Identifiant'
     'password': 'Mot de passe'
     'email': 'Mail'
-    'bank_identifier': 'Identifiant bancaire (optionnel)'
+    'bank_identifier': "Libellé des operations bancaires de remboursement (C.P.A.M, Caisse primaire d'assurance maladie...)"
```
Comment (gregorylegarec) [inline client/app/locales/fr.coffee]: Hi @ZeHiro, "opérations" misses its "é"

**Comment by gregorylegarec** [comment]
Thanks @ZeHiro 👍
