### PR TITLE
Warn the user that the password cannot be decrypted. Fixes #503

### LINKED ISSUE #503: Warn the user when the password is still encrypted.
When the DS and or the proxy are restarted, but not konnectors app, the password are encrypted (it is a bug in the DS/proxy) and konnectors tries to fetch data using the encrypted password as the real password. This leads to a fetch error. 
This should be prevented (see how Kresus manages that), and a notification shall be raised. 

Furthermore, it seems the "error" notification is deleted, which is an unexpected behaviour.

### PR DESCRIPTION
**Pull request by ZeHiro**

### CODE REVIEW

**Comment by nicofrand** [comment]
The tests are running fine on my local instance, but the output is a bit different, there are a lot of  `warn - Cozy DB | Warning : cast ignored property 'name' on 'ClassFromGetModel'`, maybe that is a difference between the Travis tests and the local tests ?

```
Konnector model
[2016-10-24 07:32:39:346] info - init | All konnectors successfully migrated
[2016-10-24 07:32:39:371] info - init | Successfully migrated all fields
    ✓ turn encrypted fields in normal fields
    ✓ remove encrypted fields from normal fields
    - updates field values properly
    - run import
    - mix model and configuration data
    - build the konnector list to display
    - run double import
    - run triple import
    if the password is declared encrypted by the data-system,
      and there is no account
warn - Cozy DB | Warning : cast ignored property 'name' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'name' on 'ClassFromGetModel'
        ✓ runImport should result with no error
      and there is an account,
warn - Cozy DB | Warning : cast ignored property 'name' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'name' on 'ClassFromGetModel'
        ✓ runImport should result with an error

  Convertion konnector models field values from < 0.6 to >= 0.6
    Field convertion
warn - Cozy DB | Warning : cast ignored property 'name' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'name' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'fields' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'fields' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'models' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'models' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'fetchOperations' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'fetchOperations' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'description' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'description' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'logger' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'logger' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'fetch' on 'ClassFromGetModel'
warn - Cozy DB | Warning : cast ignored property 'fetch' on 'ClassFromGetModel'
      ✓ fieldValues field => accounts field

```

**Comment by ZeHiro** [comment]
@nicofrand it's not that. The warning is thrown when the retrieved docType object has more properties than the one declared in konnectors

File: server/models/konnector.coffee [hunk 1]
```diff
@@ -148,7 +153,13 @@ Konnector::runImport = (values, callback) ->
     else
         konnectorModule = konnectorHash[@slug]
 
+        # Only raise the error if there is an account for this konnector
+        if @shallRaisEncryptsFieldError()
```
Comment (ZeHiro) [inline server/models/konnector.coffee]: indeeed. i'll fix
